- Hostname: rt1
  Username: noc
  Password: noc
  EnablePassword: noc
  DeviceType: CER
  KeyFile: key
  StrictHostCheck: False
  SpeedMode: False
  FileName: brocade_scripts/bgp_sum
  ExecMode: True
- Hostname: rt2
  Username: mucuser
  Password: mucpass
  EnablePassword: enablePass
  DeviceType: MLX
